version: "3"
services:
  mine_develop:
    container_name: mine_develop
    hostname: mine_develop
    image: littleof/php:8.0-swoole
    volumes:
      - ./:/app-src/
    ports:
      - 9501:9501
      - 9502:9502
      - 9503:9503
    restart: on-failure
    environment:
      - APP_ENV=dev  #节点名称
      - APP_NAME=MineAdmin #节点名称
      - APP_VERSION=1.0 #节点版本
      - APP_DEBUG=true #节点是否debug模式
      - APP_NODE=NODE1 #节点url
    network_mode: bridge
    # entrypoint: ["php", "bin/hyperf.php", "start"]
    command:
      - bash
      - -c
      - |
        php -v
        php --ri swoole
        php -m
        cd /app-src
        composer install -o
        composer dump-autoload -o
        rm -rf runtime/container
        php bin/hyperf.php server:watch
  # mine_develop_redis:
  #   container_name: mine_develop_redis
  #   hostname: mine_develop_redis
  #   image: redis:latest
  #   env_file: env.cnf
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"
  #   restart: always
  #   network_mode: bridge
  # mine_develop_db:
  #   container_name: mine_develop_db
  #   hostname: mine_develop_db
  #   image: mysql:latest
  #   env_file: env.cnf
  #   volumes:
  #     - "./data/mysql:/var/lib/mysql:rw"
  #     - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"
  #   ports:
  #     - "3306:3306"
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password --skip-external-locking
  #   network_mode: bridge
  # mine_develop_rabbit:
  #   container_name: mine_develop_rabbit
  #   hostname: mine_develop_rabbit
  #   image: rabbitmq:management
  #   env_file: env.cnf
  #   volumes:
  #     - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"
  #   ports:
  #     - 15672:15672
  #     - 5672:5672
  #     - 25672:25672
  #     - 61613:61613
  #     - 1883:1883
  #   restart: always
  #   network_mode: bridge
