version: "3"
services:
  mine_develop:
    container_name: mine_develop
    hostname: mine_develop
    image: littleof/php:8.1-cli-swoole
    volumes:
      - ./:/app-src/
    ports:
      - "9511:9501"
      - "9522:9502"
    restart: on-failure
    environment:
      - NODE=dev  #节点名称
    network_mode: bridge
    command:
      - bash
      - -c
      - |
        cd /app-src
        composer install -o
        composer dump-autoload -o
        rm -rf runtime/container
        php bin/hyperf.php server:watch

  mine_develop_redis:
    container_name: mine_develop_redis
    hostname: mine_develop_redis
    image: redis:latest
    env_file: cnf
    ports:
      - "9379:6379"
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"
    restart: always
    network_mode: bridge
  mine_develop_db:
    container_name: mine_develop_db
    hostname: mine_develop_db
    image: mysql:latest
    env_file: cnf
    volumes:
      - "./data/mysql:/var/lib/mysql:rw"
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"
    ports:
      - "9306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password --skip-external-locking
    network_mode: bridge
  mine_develop_rabbit:
    container_name: mine_develop_rabbit
    hostname: mine_develop_rabbit
    image: rabbitmq:management
    env_file: cnf
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
      - 61613:61613
      - 1883:1883
    restart: always
    network_mode: bridge
