services:
  # 首先下载前端，https://gitee.com/mineadmin/mineadmin-vue
  # 在后端根目录建立mine-ui目录，把前端文件复制过来。
  # 容器内访问宿主机的地址用：host.docker.internal
  # 宿主机也可以在hosts文件添加：127.0.0.1 host.docker.internal
  # mine-ui的.env.development文件127.0.0.1替换为host.docker.internal
  nginx-frontend:
    container_name: mine-nginx
    image: nginx:latest
    environment:
      - "TIMEZONE=Asia/Shanghai"
    ports:
      - 8101:80
    volumes:
      - ./mine-ui/dist:/usr/share/nginx/html
      - ./docker/nginx-frontend/servers:/etc/nginx/conf.d

  # mineadmin的.env的mysql、redis如果连接到宿主机，地址用：host.docker.internal
  # 如果是连接到docker内服务，则用服务名称，如:redis
  hyperf:
    container_name: mine-admin
    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    restart: always
    environment:
      - "TIMEZONE=Asia/Shanghai"
      - "APP_PROJECT=hyperf"
      - "APP_SYSTEM_ENV=docker"
    working_dir: "/opt/www"
    ports:
      - 9501:9501
      - 9502:9502
      - 9503:9503
    volumes:
      - ./:/opt/www
    entrypoint: ["php", "watch", "-c"]

  # 没有将volumes映射出来，需要持久化自行百度一下

  mysql:
    container_name: mine-mysql
    environment:
      - "TZ=Asia/Shanghai"
      - MYSQL_ROOT_PASSWORD=12345678
      - "explicit_defaults_for_timestamp=true"
      - "lower_case_table_names=1"
    image: mysql:8.0
    restart: always
    volumes: #持久化
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/mineadmin_backup.sql:/docker-entrypoint-initdb.d/mineadmin_backup.sql  # 将本地的初始化脚本目录挂载到容器中
      - ./docker/mysql/logs:/var/lib/mysql/logs #数据库日志
    ports:
        - "3306:3306"  # 确保端口映射允许宿主机上的应用连接到 MySQL
    command: "--default-authentication-plugin=caching_sha2_password --max_connections=200 --slow_query_log=1 --slow_query_log_file=/var/lib/mysql/logs/slow_query.log --long_query_time=1"
    # max_connections 最大连接数
    # slow_query_log 开始慢查询日志
    # slow_query_log_file 慢查询日志路径
    # long_query_time 慢查询阈值
  pgsql:
    container_name: mine-pgsql
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
  redis:
    image: redis
    container_name: mine-redis
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:management
    container_name: mine-rabbitmq
    restart: always
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    environment:
      - RABBITMQ_DEFAULT_USER=mineadmin
      - RABBITMQ_DEFAULT_PASS=123456
volumes:
  mysql-data: