name: Deploy to Gitee

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config user.email "xutongle@msn.com"
          git config user.name "xmo"
          git remote rm origin
          git remote add origin https://xmo:${{ secrets.GITEE_TOKEN }}@gitee.com/xmo/MineAdmin.git
          git push -f origin master